[theme]
primaryColor = "#d8240c"            # A green primary color
backgroundColor = "#fffefa"         # Light grey background
secondaryBackgroundColor = "#ffffff" # White for container backgrounds
textColor = "#202020"               # Dark grey text color